version: "3"

services:
    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports: [443:443]
        depends_on: [wordpress]
        restart: always
        volumes: [wordpress:/var/www/]
        networks: [jinigo]
    mariadb:
        build: requirements/mariadb/
        container_name: mariadb
        restart: always
        volumes: [mariadb:/var/lib/mysql]
        env_file: [.env]
        networks: [jinigo]
    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        depends_on: [mariadb]
        restart: always
        volumes: [wordpress:/var/www/]
        env_file: [.env]
        networks: [jinigo]

volumes:
    wordpress: {name: wordpress, driver: local, driver_opts: {type: none, o: bind, device: /home/jinigo/data/wordpress}}
    mariadb: {name: mariadb, driver: local, driver_opts: {type: none, o: bind, device: /home/jinigo/data/mariadb}}

networks: { jinigo: { driver: bridge } }
